In [1]:
%load_ext autotime

import scarf

scarf.__version__

'1.0.0'

time: 1.56 s (started: 2026-07-04 09:47:24 +02:00)

In [2]:
scarf.fetch_dataset(
    dataset_name="tenx_8K_pbmc_citeseq", save_path="scarf_datasets", as_zarr=True
)

time: 30.8 s (started: 2026-07-04 09:47:26 +02:00)

In [3]:
ds = scarf.DataStore("scarf_datasets/tenx_8K_pbmc_citeseq/data.zarr", nthreads=4)

time: 388 ms (started: 2026-07-04 09:47:55 +02:00)

In [4]:
ds.show_zarr_tree(depth=1)

/
├── ADT
│   ├── counts (7865, 17) uint32
│   ├── featureData
│   └── normed__I__I
├── RNA
│   ├── counts (7865, 33538) uint32
│   ├── featureData
│   ├── markers
│   ├── normed__I__hvgs
│   └── summary_stats_I
└── cellData
    ├── ADT_UMAP1 (7865,) float32
    ├── ADT_UMAP2 (7865,) float32
    ├── ADT_leiden_cluster (7865,) int64
    ├── ADT_nCounts (7865,) float64
    ├── ADT_nFeatures (7865,) float64
    ├── I (7865,) bool
    ├── RNA_UMAP1 (7865,) float32
    ├── RNA_UMAP2 (7865,) float32
    ├── RNA_cluster (7865,) int64
    ├── RNA_leiden_cluster (7865,) int64
    ├── RNA_nCounts (7865,) float64
    ├── RNA_nFeatures (7865,) float64
    ├── RNA_percentMito (7865,) float64
    ├── RNA_percentRibo (7865,) float64
    ├── RNA_tSNE1 (7865,) float64
    ├── RNA_tSNE2 (7865,) float64
    ├── ids (7865,) <U18
    └── names (7865,) <U18

time: 51.7 ms (started: 2026-07-04 09:47:56 +02:00)

In [5]:
ds.show_zarr_tree(start="cellData")

/cellData
├── ADT_UMAP1 (7865,) float32
├── ADT_UMAP2 (7865,) float32
├── ADT_leiden_cluster (7865,) int64
├── ADT_nCounts (7865,) float64
├── ADT_nFeatures (7865,) float64
├── I (7865,) bool
├── RNA_UMAP1 (7865,) float32
├── RNA_UMAP2 (7865,) float32
├── RNA_cluster (7865,) int64
├── RNA_leiden_cluster (7865,) int64
├── RNA_nCounts (7865,) float64
├── RNA_nFeatures (7865,) float64
├── RNA_percentMito (7865,) float64
├── RNA_percentRibo (7865,) float64
├── RNA_tSNE1 (7865,) float64
├── RNA_tSNE2 (7865,) float64
├── ids (7865,) <U18
└── names (7865,) <U18

  RNA_percentMito: shape=(7865,), dtype=float64, chunks=(100000,)
  RNA_tSNE2: shape=(7865,), dtype=float64, chunks=(100000,)
  ADT_nFeatures: shape=(7865,), dtype=float64, chunks=(100000,)
  ADT_UMAP2: shape=(7865,), dtype=float32, chunks=(100000,)
  ADT_UMAP1: shape=(7865,), dtype=float32, chunks=(100000,)
  names: shape=(7865,), dtype=<U18, chunks=(100000,)
  RNA_tSNE1: shape=(7865,), dtype=float64, chunks=(100000,)
  RNA_percentRibo: shape=(7865,), dtype=float64, chunks=(100000,)
  I: shape=(7865,), dtype=bool, chunks=(100000,)
  ADT_nCounts: shape=(7865,), dtype=float64, chunks=(100000,)
  RNA_nCounts: shape=(7865,), dtype=float64, chunks=(100000,)
  RNA_cluster: shape=(7865,), dtype=int64, chunks=(100000,)
  RNA_nFeatures: shape=(7865,), dtype=float64, chunks=(100000,)
  RNA_leiden_cluster: shape=(7865,), dtype=int64, chunks=(100000,)
  ids: shape=(7865,), dtype=<U18, chunks=(100000,)
  RNA_UMAP2: shape=(7865,), dtype=float32, chunks=(100000,)
  ADT_leiden_cluster: shape=(7865,), dtype=int64, chunks=(100000,)
  RNA_UMAP1: shape=(7865,), dtype=float32, chunks=(100000,)
time: 80.7 ms (started: 2026-07-04 09:47:56 +02:00)

In [6]:
ds.show_zarr_tree(start="RNA", depth=1)

/RNA
├── counts (7865, 33538) uint32
├── featureData
│   ├── I (33538,) bool
│   ├── I__hvgs (33538,) bool
│   ├── dropOuts (33538,) int64
│   ├── ids (33538,) <U15
│   ├── nCells (33538,) int64
│   └── names (33538,) <U16
├── markers
│   └── I__RNA_cluster
├── normed__I__hvgs
│   ├── data (7549, 1995) float64
│   └── reduction__pca__30__I
└── summary_stats_I
    ├── avg (33538,) float64
    ├── c_var__200__0.1 (33538,) float64
    ├── normed_n (33538,) float64
    ├── normed_tot (33538,) float64
    ├── nz_mean (33538,) float64
    └── sigmas (33538,) float64

  counts: shape=(7865, 33538), dtype=uint32, chunks=(2000, 1000)
time: 37 ms (started: 2026-07-04 09:47:56 +02:00)

In [7]:
ds.show_zarr_tree(start="RNA/featureData", depth=1)

/RNA/featureData
├── I (33538,) bool
├── I__hvgs (33538,) bool
├── dropOuts (33538,) int64
├── ids (33538,) <U15
├── nCells (33538,) int64
└── names (33538,) <U16

  names: shape=(33538,), dtype=<U16, chunks=(100000,)
  I: shape=(33538,), dtype=bool, chunks=(100000,)
  nCells: shape=(33538,), dtype=int64, chunks=(100000,)
  I__hvgs: shape=(33538,), dtype=bool, chunks=(100000,)
  ids: shape=(33538,), dtype=<U15, chunks=(100000,)
  dropOuts: shape=(33538,), dtype=int64, chunks=(100000,)
time: 26.5 ms (started: 2026-07-04 09:47:56 +02:00)

In [8]:
ds.cells.head()

,I,ids,names,RNA_percentMito,RNA_tSNE2,ADT_nFeatures,ADT_UMAP2,RNA_tSNE1,ADT_UMAP1,RNA_percentRibo,RNA_nCounts,RNA_nFeatures,ADT_nCounts,RNA_cluster,RNA_leiden_cluster,ADT_leiden_cluster,RNA_UMAP2,RNA_UMAP1
0,True,AAACCCAAGATTGTGA-1,AAACCCAAGATTGTGA-1,8.668831,-18.08830,17.0,9.510007,-4.26865,-13.884989,15.259740,6160.0,2194.0,981.0,4,3,16,-7.417822,29.421942
1,True,AAACCCACATCGGTTA-1,AAACCCACATCGGTTA-1,6.316103,-14.88920,17.0,10.784672,5.02671,-5.097915,19.037688,6713.0,2093.0,1475.0,4,3,15,-12.649998,30.801842
2,True,AAACCCAGTACCGCGT-1,AAACCCAGTACCGCGT-1,8.056090,-18.83030,17.0,12.961405,-14.91320,-7.885502,16.002200,3637.0,1518.0,7149.0,5,5,9,4.256729,29.397541
3,True,AAACCCAGTATCGAAA-1,AAACCCAGTATCGAAA-1,9.003215,-3.35003,17.0,11.531997,16.69630,12.072053,18.729904,1244.0,737.0,6831.0,3,4,2,-32.227364,5.441914
4,True,AAACCCAGTCGTCATA-1,AAACCCAGTCGTCATA-1,6.204519,-1.37607,17.0,12.290624,18.37000,13.928782,16.353887,2611.0,1240.0,6839.0,3,4,2,-30.397615,7.166490

time: 486 ms (started: 2026-07-04 09:47:56 +02:00)

In [9]:
ds.RNA.feats.head()

       I              ids        names  nCells  I__hvgs  dropOuts
0  False  ENSG00000243485  MIR1302-2HG       0    False      7865
1  False  ENSG00000237613      FAM138A       0    False      7865
2  False  ENSG00000186092        OR4F5       0    False      7865
3  False  ENSG00000238009   AL627309.1      12    False      7853
4  False  ENSG00000239945   AL627309.3       0    False      7865

time: 74.1 ms (started: 2026-07-04 09:47:56 +02:00)

In [10]:
ds.cells.to_pandas_dataframe(
    columns=["ids", "RNA_UMAP1", "RNA_UMAP2", "RNA_cluster"]
).set_index("ids")

                    RNA_UMAP1  RNA_UMAP2  RNA_cluster
ids
AAACCCAAGATTGTGA-1  29.421942  -7.417822            4
AAACCCACATCGGTTA-1  30.801842 -12.649998            4
AAACCCAGTACCGCGT-1  29.397541   4.256729            5
AAACCCAGTATCGAAA-1   5.441914 -32.227364            3
AAACCCAGTCGTCATA-1   7.166490 -30.397615            3
...                       ...        ...          ...
TTTGTTGGTTCAAGTC-1  -5.545609  21.742104           18
TTTGTTGGTTGCATGT-1 -26.972895  -0.762715            9
TTTGTTGGTTGCGGCT-1  27.239552  -5.230516            4
TTTGTTGTCGAGTGAG-1 -23.030291 -20.647554            2
TTTGTTGTCGTTCAGA-1 -10.845096  -2.644977            2

[7865 rows x 3 columns]

time: 109 ms (started: 2026-07-04 09:47:57 +02:00)

In [11]:
clusters = ds.cells.fetch("RNA_cluster")
clusters.shape

(7549,)

time: 64.1 ms (started: 2026-07-04 09:47:57 +02:00)

In [12]:
clusters_all = ds.cells.fetch_all("RNA_cluster")
clusters_all.shape

(7865,)

time: 23.9 ms (started: 2026-07-04 09:47:57 +02:00)

In [13]:
is_clust_1 = (
    clusters == 1
)  # is_clust_1 has just 7549 elements (same as the number of cells with value True in `I`)
ds.cells.insert(column_name="is_clust1", values=is_clust_1)

time: 68.1 ms (started: 2026-07-04 09:47:57 +02:00)

In [14]:
ds.cells.insert(column_name="is_clust1", values=is_clust_1)

ValueError: ERROR: is_clust1 already exists. Please set `overwrite` to True to overwrite.

time: 148 ms (started: 2026-07-04 09:47:57 +02:00)

In [15]:
ds.cells.insert(column_name="is_clust1", values=is_clust_1, overwrite=True)

time: 64 ms (started: 2026-07-04 09:47:57 +02:00)

In [16]:
ds.RNA.rawData

ChunkedArray(shape=(7865, 33538), dtype=uint32, chunksize=(2000, 33538), numblocks=4)

time: 1.52 ms (started: 2026-07-04 09:47:57 +02:00)

In [17]:
ds.RNA.normed()

ChunkedArray(shape=(7549, 13550), dtype=float64, chunksize=(2000, 13550), numblocks=4)

time: 104 ms (started: 2026-07-04 09:47:57 +02:00)

In [18]:
ds.RNA.normMethod

time: 1.86 ms (started: 2026-07-04 09:47:57 +02:00)

In [19]:
import inspect

print(inspect.getsource(ds.RNA.normMethod))

def norm_lib_size(assay: "Assay", counts: ChunkedArray) -> ChunkedArray:
    """Performs library size normalization on the data. This is the default
    method for RNA assays.

    Args:
        assay: An instance of the assay object
        counts: A chunked array with raw counts data

    Returns:  A chunked array (delayed matrix) containing normalized data.
    """
    assert assay.sf is not None and assay.scalar is not None
    return assay.sf * counts / assay.scalar.reshape(-1, 1)

time: 14.4 ms (started: 2026-07-04 09:47:57 +02:00)

In [20]:
def my_cool_normalization_method(assay, counts):
    import numpy as np

    # Calculate total counts for each cell
    lib_size = counts.sum(axis=1).reshape(-1, 1)

    # Library size normalization followed by log2 transformation
    return np.log2(counts / lib_size)


ds.RNA.normMethod = my_cool_normalization_method

time: 375 μs (started: 2026-07-04 09:47:57 +02:00)

In [21]:
ds.RNA.normMethod = scarf.assay.norm_dummy

time: 359 μs (started: 2026-07-04 09:47:57 +02:00)

In [22]:
ds.show_zarr_tree(start="RNA/normed__I__hvgs")

/RNA/normed__I__hvgs
├── data (7549, 1995) float64
└── reduction__pca__30__I
    ├── ann__l2__63__63__48__4466
    │   └── knn__21
    ├── kmeans__100__4466
    │   ├── cluster_centers (100, 30) float64
    │   └── cluster_labels (7549,) float64
    ├── mu (1995,) float64
    ├── reduction (1995, 30) float64
    └── sigma (1995,) float64

  data: shape=(7549, 1995), dtype=float64, chunks=(2000, 2000)
time: 42 ms (started: 2026-07-04 09:47:57 +02:00)

/home/parashar/scarf/.venv/lib/python3.12/site-packages/zarr/core/group.py:3289: ZarrUserWarning: Object at ann_idx is not recognized as a component of a Zarr hierarchy.
  warnings.warn(

In [23]:
ds.load_graph(
    from_assay="RNA", cell_key="I", feat_key="hvgs", symmetric=False, upper_only=False
)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 158529 stored elements and shape (7549, 7549)>

time: 26.5 ms (started: 2026-07-04 09:47:57 +02:00)

In [24]:
ds.show_zarr_tree(start="RNA/markers", depth=2)

/RNA/markers
└── I__RNA_cluster
    ├── 1
    │   ├── feature_index (13550,) int64
    │   ├── fold_change (13550,) float64
    │   ├── frac_exp (13550,) float64
    │   ├── frac_exp_rest (13550,) float64
    │   ├── mean (13550,) float64
    │   ├── mean_rest (13550,) float64
    │   └── score (13550,) float64
    ├── 10
    │   ├── feature_index (13550,) int64
    │   ├── fold_change (13550,) float64
    │   ├── frac_exp (13550,) float64
    │   ├── frac_exp_rest (13550,) float64
    │   ├── mean (13550,) float64
    │   ├── mean_rest (13550,) float64
    │   └── score (13550,) float64
    ├── 11
    │   ├── feature_index (13550,) int64
    │   ├── fold_change (13550,) float64
    │   ├── frac_exp (13550,) float64
    │   ├── frac_exp_rest (13550,) float64
    │   ├── mean (13550,) float64
    │   ├── mean_rest (13550,) float64
    │   └── score (13550,) float64
    ├── 12
    │   ├── feature_index (13550,) int64
    │   ├── fold_change (13550,) float64
    │   ├── frac_exp (13550,) float64
    │   ├── frac_exp_rest (13550,) float64
    │   ├── mean (13550,) float64
    │   ├── mean_rest (13550,) float64
    │   └── score (13550,) float64
    ├── 13
    │   ├── feature_index (13550,) int64
    │   ├── fold_change (13550,) float64
    │   ├── frac_exp (13550,) float64
    │   ├── frac_exp_rest (13550,) float64
    │   ├── mean (13550,) float64
    │   ├── mean_rest (13550,) float64
    │   └── score (13550,) float64
    ├── 14
    │   ├── feature_index (13550,) int64
    │   ├── fold_change (13550,) float64
    │   ├── frac_exp (13550,) float64
    │   ├── frac_exp_rest (13550,) float64
    │   ├── mean (13550,) float64
    │   ├── mean_rest (13550,) float64
    │   └── score (13550,) float64
    ├── 15
    │   ├── feature_index (13550,) int64
    │   ├── fold_change (13550,) float64
    │   ├── frac_exp (13550,) float64
    │   ├── frac_exp_rest (13550,) float64
    │   ├── mean (13550,) float64
    │   ├── mean_rest (13550,) float64
    │   └── score (13550,) float64
    ├── 16
    │   ├── feature_index (13550,) int64
    │   ├── fold_change (13550,) float64
    │   ├── frac_exp (13550,) float64
    │   ├── frac_exp_rest (13550,) float64
    │   ├── mean (13550,) float64
    │   ├── mean_rest (13550,) float64
    │   └── score (13550,) float64
    ├── 17
    │   ├── feature_index (13550,) int64
    │   ├── fold_change (13550,) float64
    │   ├── frac_exp (13550,) float64
    │   ├── frac_exp_rest (13550,) float64
    │   ├── mean (13550,) float64
    │   ├── mean_rest (13550,) float64
    │   └── score (13550,) float64
    ├── 18
    │   ├── feature_index (13550,) int64
    │   ├── fold_change (13550,) float64
    │   ├── frac_exp (13550,) float64
    │   ├── frac_exp_rest (13550,) float64
    │   ├── mean (13550,) float64
    │   ├── mean_rest (13550,) float64
    │   └── score (13550,) float64
    ├── 19
    │   ├── feature_index (13550,) int64
    │   ├── fold_change (13550,) float64
    │   ├── frac_exp (13550,) float64
    │   ├── frac_exp_rest (13550,) float64
    │   ├── mean (13550,) float64
    │   ├── mean_rest (13550,) float64
    │   └── score (13550,) float64
    ├── 2
    │   ├── feature_index (13550,) int64
    │   ├── fold_change (13550,) float64
    │   ├── frac_exp (13550,) float64
    │   ├── frac_exp_rest (13550,) float64
    │   ├── mean (13550,) float64
    │   ├── mean_rest (13550,) float64
    │   └── score (13550,) float64
    ├── 20
    │   ├── feature_index (13550,) int64
    │   ├── fold_change (13550,) float64
    │   ├── frac_exp (13550,) float64
    │   ├── frac_exp_rest (13550,) float64
    │   ├── mean (13550,) float64
    │   ├── mean_rest (13550,) float64
    │   └── score (13550,) float64
    ├── 3
    │   ├── feature_index (13550,) int64
    │   ├── fold_change (13550,) float64
    │   ├── frac_exp (13550,) float64
    │   ├── frac_exp_rest (13550,) float64
    │   ├── mean (13550,) float64
    │   ├── mean_rest (13550,) float64
    │   └── score (13550,) float64
    ├── 4
    │   ├── feature_index (13550,) int64
    │   ├── fold_change (13550,) float64
    │   ├── frac_exp (13550,) float64
    │   ├── frac_exp_rest (13550,) float64
    │   ├── mean (13550,) float64
    │   ├── mean_rest (13550,) float64
    │   └── score (13550,) float64
    ├── 5
    │   ├── feature_index (13550,) int64
    │   ├── fold_change (13550,) float64
    │   ├── frac_exp (13550,) float64
    │   ├── frac_exp_rest (13550,) float64
    │   ├── mean (13550,) float64
    │   ├── mean_rest (13550,) float64
    │   └── score (13550,) float64
    ├── 6
    │   ├── feature_index (13550,) int64
    │   ├── fold_change (13550,) float64
    │   ├── frac_exp (13550,) float64
    │   ├── frac_exp_rest (13550,) float64
    │   ├── mean (13550,) float64
    │   ├── mean_rest (13550,) float64
    │   └── score (13550,) float64
    ├── 7
    │   ├── feature_index (13550,) int64
    │   ├── fold_change (13550,) float64
    │   ├── frac_exp (13550,) float64
    │   ├── frac_exp_rest (13550,) float64
    │   ├── mean (13550,) float64
    │   ├── mean_rest (13550,) float64
    │   └── score (13550,) float64
    ├── 8
    │   ├── feature_index (13550,) int64
    │   ├── fold_change (13550,) float64
    │   ├── frac_exp (13550,) float64
    │   ├── frac_exp_rest (13550,) float64
    │   ├── mean (13550,) float64
    │   ├── mean_rest (13550,) float64
    │   └── score (13550,) float64
    └── 9
        ├── feature_index (13550,) int64
        ├── fold_change (13550,) float64
        ├── frac_exp (13550,) float64
        ├── frac_exp_rest (13550,) float64
        ├── mean (13550,) float64
        ├── mean_rest (13550,) float64
        └── score (13550,) float64

time: 176 ms (started: 2026-07-04 09:47:57 +02:00)

In [25]:
ds.get_markers(group_key="RNA_cluster", group_id=7, min_score=0.1, min_frac_exp=0.1)

,group_id,feature_name,score,mean,mean_rest,frac_exp,frac_exp_rest,fold_change
0,7,KLRB1,0.29927,14.13947,0.85409,0.98158,0.18971,16.55494
1,7,GZMK,0.18346,5.50526,0.52044,0.98421,0.10852,10.57819
2,7,IL7R,0.14324,7.44737,2.40312,0.97895,0.43186,3.09904
3,7,DUSP2,0.13970,4.54737,0.68726,0.88947,0.29739,6.61662
4,7,NCR3,0.10281,1.66053,0.19529,0.74737,0.13544,8.50308
5,7,KLRG1,0.10096,1.72632,0.24578,0.79737,0.15274,7.02381

time: 218 ms (started: 2026-07-04 09:47:57 +02:00)

In [26]:
ds.export_markers_to_csv(
    group_key="RNA_cluster", csv_filename="test.csv", min_score=0.2, min_frac_exp=0.1
)

time: 3.84 s (started: 2026-07-04 09:47:58 +02:00)